services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brigadas-laravel
    volumes:
      - .:/var/www
    environment:
      # Database
      DB_CONNECTION: pgsql
      DB_HOST: db       # Nombre del servicio del contenedor de postgres
      DB_PORT: 5432
      DB_DATABASE: brigadas_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      APP_URL: http://brigadas.dasalas.shop
      SESSION_DRIVER: file
      SESSION_DOMAIN: brigadas.dasalas.shop
      SESSION_SECURE_COOKIE: false
      # Session Configuration (FIX for 419 error)
      # SESSION_DRIVER: database
      # SESSION_LIFETIME: 120
      # SESSION_DOMAIN: .dasalas.shop
      # SESSION_SECURE_COOKIE: "false"
      
      # App Configuration
      # APP_URL: http://brigadas.dasalas.shop
      # APP_ENV: production
      
      # Microservices
      ANIMAL_REPORTS_API_URL: http://rescate.dasalas.shop/
      INVENTORY_API_URL: http://donaciones.dasalas.shop/
      DAS_API_URL: http://gatealas.dasalas.shop/api/gateway/logistica/paquetes/solicitud-publica
    depends_on:
      - db
    networks:
      - brigadas-net
  nginx:
    image: nginx:latest
    container_name: brigadas
    expose:
      - "80"
    # ports:
    #   - "8080:80" #---> despliegue local con puerto 8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - brigadas-net
      - internal-network
      - proxy-network
  db:
    image: postgis/postgis:16-3.4
    container_name: brigadas-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: brigadas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - brigadas-net

networks:
  brigadas-net:
    driver: bridge
  internal-network:
    external: true
  proxy-network:
    external: true

volumes:
  db-data: